### ISSUE TITLE
Flickering when re-spawning part of the UI

### ISSUE THREAD

**Issue by umut-sahin** [UmbraLuminosa/sickle_ui#118]
I have a market screen in my game. I've structured the market screen to respawn the UI for offered items, when market state is changed. I do this by:
- despawning descendants of `OfferingsContainer` ([here](https://github.com/umut-sahin/mythmallow/blob/1d5b999dac39d29258bd580d89c545183be3cd67/core/logic/src/systems/ui/market_screen.rs#L327-L328))
- spawning new `OfferingContainer`s under `OfferingsContainer` ([here](https://github.com/umut-sahin/mythmallow/blob/1d5b999dac39d29258bd580d89c545183be3cd67/core/logic/src/systems/ui/market_screen.rs#L330-L396)) 

Previously, this logic was done with `bevy_ui` and it was working as it should. I'm in a almost rewrite of the project and I've decided to use `sickle_ui` to simplify UI logic. Now, there is a delay between despawn and new spawns, so the market UI flickers:
![Peek 2024-09-28 12-22](https://github.com/user-attachments/assets/2cd6e8b4-f0e2-411c-9d5f-e5ac380a6713)

I'm not sure what the problem is. It might also be unrelated to `sickle_ui`, so sorry if it was because of something else I did. Please let me know if you have any idea why this might be happening.

I'd be more than happy to provide more information, and thank you for the amazing library <3

**Comment by eidloi** [comment]
Ahoy @umut-sahin! I don't see anything _obviously_ wrong with the code. Internally `sickle_ui` is just using Bevy standard spawn/with_children commands, so that should not cause the flicker. Scheduling is also not an issue since the despawn and respawn is in the same system.

Perhaps the translation needs a frame to fill in the texts? I mean, the boxes and buttons don't disappear, only the text flickers.

**Comment by umut-sahin** [comment]
> Perhaps the translation needs a frame to fill in the texts? I mean, the boxes and buttons don't disappear, only the text flickers.

Unfortunately they do, GIF wasn't able to capture it. Here is a slow-mo video that I've captured with my phone:
 
https://github.com/user-attachments/assets/8c51d5bf-44af-4832-83a9-3eb5836a50f1

Similar logic works in main:

https://github.com/user-attachments/assets/86db9df1-b81d-457a-8451-9871084326a5

With the following code:
- https://github.com/umut-sahin/mythmallow/blob/52c830a57da3f7a18ee3ccb61419459175b8ade6/game/src/ui/market/systems.rs#L501-L506
- https://github.com/umut-sahin/mythmallow/blob/52c830a57da3f7a18ee3ccb61419459175b8ade6/game/src/ui/market/systems.rs#L355-L366

Though there are subtle differences between main and refactor. Anything caught your attention?

**Comment by eidloi** [comment]
no, nothing in particular, however do you know the actual bevy version you are running on? There used to be an issue with adding / removing children that caused layout bugs in weird cases, which should be fixed in [0.14.1](https://github.com/bevyengine/bevy/pull/14490).

Also, if the entire thing is popping, is it possible that your market data gets emptied for a frame before it repopulates?

**Comment by umut-sahin** [comment]
I thought about that but it's not the case. When I put:
```rust
pub fn update_offerings(
    mut commands: Commands,
    market_offerings_container_query: Query<Entity, With<MarketScreenOfferingsContainer>>,
    balance: Res<Balance>,
    market_state: Res<MarketState>,
    item_registry: Res<ItemRegistry>,
    localization: Res<Localization>,
    ui_font: Res<UiFont>,
) {
    let market_offerings_container_entity = match market_offerings_container_query.get_single() {
        Ok(query_result) => query_result,
        Err(_) => return,
    };

    let mut market_offerings_container = commands.entity(market_offerings_container_entity);
    market_offerings_container.despawn_descendants();

    log::error!("updating offerings");
    ...
```
I get:
```
2024-09-29T14:52:05.994634Z  INFO mythmallow_core_logic::systems::ui::market_screen: lock button of item 2 is clicked
2024-09-29T14:52:05.994642Z  INFO mythmallow_core_data::resources::market: locking item 2 in the market
2024-09-29T14:52:05.995042Z ERROR mythmallow_core_logic::systems::ui::market_screen: updating offerings
2024-09-29T14:52:06.002429Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:06.010767Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:10.779308Z  INFO mythmallow_core_logic::systems::ui::market_screen: lock button of item 2 is clicked
2024-09-29T14:52:10.779324Z  INFO mythmallow_core_data::resources::market: unlocking item 2 in the market
2024-09-29T14:52:10.779826Z ERROR mythmallow_core_logic::systems::ui::market_screen: updating offerings
2024-09-29T14:52:10.786881Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:10.795012Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:14.553551Z  INFO mythmallow_core_logic::systems::ui::market_screen: lock button of item 2 is clicked
2024-09-29T14:52:14.553559Z  INFO mythmallow_core_data::resources::market: locking item 2 in the market
2024-09-29T14:52:14.553983Z ERROR mythmallow_core_logic::systems::ui::market_screen: updating offerings
2024-09-29T14:52:14.561330Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:14.569664Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:17.520526Z  INFO mythmallow_core_logic::systems::ui::market_screen: lock button of item 2 is clicked
2024-09-29T14:52:17.520534Z  INFO mythmallow_core_data::resources::market: unlocking item 2 in the market
2024-09-29T14:52:17.521094Z ERROR mythmallow_core_logic::systems::ui::market_screen: updating offerings
2024-09-29T14:52:17.528330Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:17.536742Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-29T14:52:19.399332Z  INFO bevy_window::system: No windows are open, exiting
2024-09-29T14:52:19.399971Z  INFO bevy_winit::system: Closing window Entity { index: 0, generation: 1 }
```
(with a click around each 4 seconds)

So
```rust
market_offerings_container.despawn_descendants();
```
Gets called exactly number of clicks times.

Bevy version was:
```
[[package]]
name = "bevy"
version = "0.14.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "c8ece0d8dde51890fb52dcba5b04fd1c657617a4022908c327b2d6e83d173a32"
dependencies = [
 "bevy_dylib",
 "bevy_internal",
]
```

Just tried with `v0.14.2`, issue is still there.

**Comment by eidloi** [comment]
you can try `apply_deferred` after the `update_offerings` and inject a debug system that dumps the hierarchy (`commands.log_hierarchy`, you can pass in a filter to reduce the wall of text), just to see what exactly gets spawned.

**Comment by umut-sahin** [comment]
I did:
```rust
        fn dump_hierarchy(entities: Query<(&Name, Option<&Parent>)>) {
            let mut hierarchy = HashMap::<&str, Vec<&str>>::default();
            for (name, parent) in entities.iter() {
                hierarchy.entry(name.as_str()).or_default();
                if let Some(parent) = parent {
                    if let Ok((parent_name, _)) = entities.get(parent.get()) {
                        hierarchy.entry(parent_name.as_str()).or_default().push(name.as_str());
                    }
                }
            }
            log::warn!("{:#?}", hierarchy.get("Offerings"));
        }

        app.add_systems(
            Last,
            (dump_hierarchy, update_offerings, apply_deferred, dump_hierarchy).chain().run_if(
                |app_state: Res<State<AppState>>,
                 balance: Res<Balance>,
                 market_state: Res<MarketState>,
                 item_registry: Res<ItemRegistry>,
                 market_screen_offerings_container_query: Query<
                    Entity,
                    Added<MarketScreenOfferingsContainer>,
                >| {
                    app_state.get() == &AppState::Game
                        && (balance.is_changed()
                            || market_state.is_changed()
                            || item_registry.is_changed()
                            || !market_screen_offerings_container_query.is_empty())
                },
            ),
        );
```

And the results seems to be what's expected:
```
2024-09-30T08:58:53.719523Z  INFO mythmallow_core_logic::systems::ui::market_screen: refresh button is clicked
2024-09-30T08:58:53.719532Z  INFO mythmallow_core_data::resources::item: spending 1.00 $ to refresh the market
2024-09-30T08:58:53.719535Z  INFO mythmallow_core_data::resources::item: new balance is 8.00 $
2024-09-30T08:58:53.719537Z  INFO mythmallow_core_logic::systems::ui::market_screen: new refresh cost is 1.00 $
2024-09-30T08:58:53.719549Z  INFO mythmallow_core_logic::systems::market: refreshing the market to offer 4 items
2024-09-30T08:58:53.719570Z  INFO mythmallow_core_logic::systems::market: items to offer will be selected randomly with these probabilities:
+-----------------+---------------------+-------------+
|      Item       |       Chance        | Probability |
+-----------------+---------------------+-------------+
| bident-of-hades | (1000000 / 2000000) |  50.000000% |
+-----------------+---------------------+-------------+
| bow-of-artemis  | (1000000 / 2000000) |  50.000000% |
+-----------------+---------------------+-------------+
2024-09-30T08:58:53.719572Z  INFO mythmallow_core_logic::systems::market: offering randomly selected "bident-of-hades" with 50.000000% probability (1000000 / 2000000) for 20.00 $
2024-09-30T08:58:53.719574Z  INFO mythmallow_core_logic::systems::market: offering randomly selected "bow-of-artemis" with 50.000000% probability (1000000 / 2000000) for 25.00 $
2024-09-30T08:58:53.719576Z  INFO mythmallow_core_logic::systems::market: offering randomly selected "bident-of-hades" with 50.000000% probability (1000000 / 2000000) for 20.00 $
2024-09-30T08:58:53.719577Z  INFO mythmallow_core_logic::systems::market: offering randomly selected "bident-of-hades" with 50.000000% probability (1000000 / 2000000) for 20.00 $
2024-09-30T08:58:53.719581Z  INFO mythmallow_core_logic::systems::market: market is refreshed
2024-09-30T08:58:53.720066Z  WARN mythmallow_core_logic::plugins::ui::market_screen: Some(
    [
        "Offering 1 [bident-of-hades]",
        "Offering 2 [bident-of-hades]",
        "Offering 3 [bident-of-hades]",
        "Offering 4 [bow-of-artemis]",
    ],
)
2024-09-30T08:58:53.720342Z  WARN mythmallow_core_logic::plugins::ui::market_screen: Some(
    [
        "Offering 1 [bident-of-hades]",
        "Offering 2 [bow-of-artemis]",
        "Offering 3 [bident-of-hades]",
        "Offering 4 [bident-of-hades]",
    ],
)
2024-09-30T08:58:53.727183Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
2024-09-30T08:58:53.735903Z  INFO mythmallow_core_logic::systems::ui::widget: initializing the widget structure
```

So the previous offerings are despawned and new offerings are respawned correctly. Can it be related to some kind of processing required before the ui nodes take their final position? But then why was it working with the old version?

**Comment by eidloi** [comment]
when is the update system scheduled? If you update it in `Update`, the next layout calc should take care of it in frame. If you use theming, you have to schedule the system _before_ the theming update (there is a system set for this) to apply the style im the same frame. (Theming is in `PostUpdate`, before layout)

**Comment by umut-sahin** [comment]
I'm not using theming.

I've tried the following schedules, issue is present in all of them:
- First
- PreUpdate
- Update
- PostUpdate
- Last

**Comment by eidloi** [comment]
Then I apologize but I have no clue. You can rule out `sickle_ui` by temporarily replacing the offer items with a simple colored boxes and a text inside a la vanilla bevy_ui (commands.spawn(/*...*/).with_children()) and see if that blinks. Just make sure to add your custom components to see if they cause anything unintended.

The command extensions `sickle_ui` provides don't really _do_ anything beside creating standard commands, so it might be things like other systems picking on them, app state effect, or even taffy (the layout engine of bevy) having a bad day. For instance I see the "initializing the widget structure" twice in the log in close proximity, but I can't tell if that does anything to your market screen.

**Comment by umut-sahin** [comment]
Thanks for trying! I don't have time to port it to `bevy_ui` right now, but I'll do as soon as I can and give you an update.
